name: deploy API

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
          docker build -t babaolumoh/fastapi-app:latest .
          docker push babaolumoh/fastapi-app:latest

    - name: Set up SSH key
      run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > fastapi.pem
          chmod 400 fastapi.pem

    - name: Deploy to EC2
      run: |
          ssh -o StrictHostKeyChecking=no -i fastapi.pem ubuntu@18.169.186.101 << 'EOF'
          
          docker pull babaolumoh/fastapi-app:latest

          docker stop fastapi-app || true

          docker rm fastapi-app || true

          docker run -d --name fastapi-app -p 8000:8000 babaolumoh/fastapi-app:latest
          EOF